-- NeuroHealth Nexus - Supabase Database Schema
-- Based on actual CSV column structure
-- Updated: 2026-02-09

-- 1. Reset Tables (Drop existing tables if any)
-- DROP TABLE IF EXISTS activity CASCADE;
-- DROP TABLE IF EXISTS patients CASCADE;

-- 2. Create Patients Table (Health Dataset 1)
-- Columns: Patient_Number, Blood_Pressure_Abnormality, Level_of_Hemoglobin, 
--          Genetic_Pedigree_Coefficient, Age, BMI, Sex, Pregnancy, Smoking,
--          salt_content_in_the_diet, alcohol_consumption_per_day, Level_of_Stress,
--          Chronic_kidney_disease, Adrenal_and_thyroid_disorders
CREATE TABLE IF NOT EXISTS patients (
    patient_number INT PRIMARY KEY,
    blood_pressure_abnormality INT,
    level_of_hemoglobin FLOAT,
    genetic_pedigree_coefficient FLOAT,
    age INT,
    bmi INT,
    sex INT,
    pregnancy FLOAT,
    smoking INT,
    salt_content_in_the_diet INT,
    alcohol_consumption_per_day FLOAT,
    level_of_stress INT,
    chronic_kidney_disease INT,
    adrenal_and_thyroid_disorders INT
);

-- 3. Create Activity Table (Health Dataset 2)
-- Columns: Patient_Number (FK), Day_Number, Physical_activity
CREATE TABLE IF NOT EXISTS activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_number INT NOT NULL REFERENCES patients(patient_number) ON DELETE CASCADE,
    day_number INT NOT NULL,
    physical_activity FLOAT,
    CONSTRAINT unique_patient_day UNIQUE (patient_number, day_number)
);

-- 4. Create Indexes for Performance
CREATE INDEX idx_patients_age ON patients(age);
CREATE INDEX idx_patients_ckd ON patients(chronic_kidney_disease);
CREATE INDEX idx_patients_bmi ON patients(bmi);
CREATE INDEX idx_patients_sex ON patients(sex);
CREATE INDEX idx_activity_patient ON activity(patient_number);
CREATE INDEX idx_activity_day ON activity(day_number);
CREATE INDEX idx_activity_patient_day ON activity(patient_number, day_number);

-- 5. Enable Row Level Security (RLS)
ALTER TABLE patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity ENABLE ROW LEVEL SECURITY;

-- 6. Create RLS Policies (Allow public read/insert for demo purposes)
CREATE POLICY "Public Read Access" ON patients 
    FOR SELECT USING (true);

CREATE POLICY "Public Insert Access" ON patients 
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Public Read Access" ON activity 
    FOR SELECT USING (true);

CREATE POLICY "Public Insert Access" ON activity 
    FOR INSERT WITH CHECK (true);

-- 7. Helper Function for Agent SQL Execution
CREATE OR REPLACE FUNCTION execute_sql(query_text TEXT)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    result JSON;
BEGIN
    EXECUTE 'SELECT json_agg(t) FROM (' || query_text || ') t' INTO result;
    RETURN result;
END;
$$;

-- 8. Verification Queries
-- Run these after seeding to verify data:
-- SELECT COUNT(*) FROM patients;
-- SELECT COUNT(*) FROM activity;
-- SELECT * FROM patients LIMIT 5;
-- SELECT * FROM activity WHERE patient_number IS NOT NULL LIMIT 5;
-- 
-- Verify foreign key relationships:
-- SELECT 
--     p.patient_number,
--     COUNT(a.id) as activity_count
-- FROM patients p
-- LEFT JOIN activity a ON p.patient_number = a.patient_number
-- GROUP BY p.patient_number
-- ORDER BY p.patient_number
-- LIMIT 10;
